apiVersion: 1
groups:
    - orgId: 1
      name: nginx-evaluation
      folder: nginx-alerts-rules
      interval: 30s
      rules:
        - uid: bdm5czeiwj6kgf
          title: NGINX exceeding CPU limits
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: ddl8t24cjxs74e
              model:
                editorMode: code
                expr: sum(rate(container_cpu_usage_seconds_total{namespace="challenger-005", container=~"nginx"}[1m])) / sum(kube_pod_container_resource_limits{namespace="challenger-005", container=~"nginx", resource="cpu"})
                instant: false
                intervalMs: 10000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: C
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
            - refId: B
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: mean
                refId: B
                settings:
                    mode: dropNN
                type: reduce
          dashboardUid: cdl8ui1a5hb7kd
          panelId: 4
          noDataState: NoData
          execErrState: Error
          for: 3m
          annotations:
            __dashboardUid__: cdl8ui1a5hb7kd
            __panelId__: "4"
            summary: Nginx exceeded CPU limit request
          labels:
            severity: medium
          isPaused: false
        - uid: adm5eichniq68b
          title: Http requests increased by 20%
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: ddl8t24cjxs74e
              model:
                editorMode: builder
                expr: |4
                      rate(nginx_http_requests_total{service="nginx", namespace="challenger-005"}[1m])
                      /
                      rate(nginx_http_requests_total{service="nginx", namespace="challenger-005"}[2m] offset 1m)
                instant: true
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1.2
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: cdl8ui1a5hb7kd
          panelId: 7
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: cdl8ui1a5hb7kd
            __panelId__: "7"
            summary: Http requests increased by 20%
          labels:
            severity: medium
          isPaused: false
        - uid: ednafeoyncdtse
          title: Pod Status Not Ready
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: ddl8t24cjxs74e
              model:
                disableTextWrap: false
                editorMode: code
                expr: kube_pod_status_phase{namespace="challenger-005",phase=~"Pending|Unknown", pod=~"nginx-.*"}
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: C
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 3m
          annotations:
            summary: Nginx pod is in not ready status
          labels:
            severity: high
          isPaused: false
    - orgId: 1
      name: cluster-evaluation
      folder: cluster-alerts
      interval: 1m
      rules:
        - uid: ddnadok318sn4a
          title: Nodes NotReady
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: ddl8t24cjxs74e
              model:
                editorMode: code
                expr: kube_node_status_condition{status="true",condition!="Ready"}
                instant: true
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 3m
          annotations:
            summary: Nodes in the cluster are in NotReady state
          labels:
            severity: high
          isPaused: false
        - uid: ednaoagbnuz28e
          title: Node exceeding CPU% usage
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: ddl8t24cjxs74e
              model:
                editorMode: code
                expr: sum by(instance)(rate(node_cpu_seconds_total{mode!="idle"}[1m]))*100
                instant: true
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 60
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 3m
          annotations:
            summary: Node exceeding 60% CPU usage
          labels:
            severity: medium
          isPaused: false
