{
 "title": "Nginx Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU USAGE PER INSTANCE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (\n    rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])\n  ) * 100",
     "legendFormat": "{{kube_node_info.node}}"
    }
   ]
  },
  {
   "title": "Last scrape status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{namespace=\"challenger-005\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX HTTP PROCESSED REQUESTS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "rate(nginx_connections_handled{namespace=\"challenger-005\", service=\"nginx\"}[1m])",
     "legendFormat": "HTTP processed connections"
    }
   ]
  },
  {
   "title": "NGINX HTTP TOTAL REQUESTS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{service=\"nginx\", namespace=\"challenger-005\"}[1m])",
     "legendFormat": "HTTP total requests"
    }
   ]
  },
  {
   "title": "NGINX ACTIVE CONNECTIONS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "nginx_connections_active{service=\"nginx\", namespace=\"challenger-005\"}",
     "legendFormat": "HTTP active connections"
    }
   ]
  },
  {
   "title": "CONTAINER CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"challenger-005\", pod=~\"nginx-.*\", container=\"nginx\", service=\"kube-prometheus-stack-kubelet\"}[1m])",
     "legendFormat": "{{container}} CPU usage"
    },
    {
     "expr": "(kube_pod_container_resource_requests{namespace=\"challenger-005\", pod=~\"nginx-.*\", container=\"nginx\", resource=\"cpu\"})",
     "legendFormat": "{{container}} CPU request"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"challenger-005\", pod=~\"nginx-.*\", container=\"nginx\", resource=\"cpu\"}",
     "legendFormat": "{{container}} CPU limits"
    }
   ]
  },
  {
   "title": "CONTAINER MEMORY USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"challenger-005\", pod=~\"nginx-.*\", container=\"nginx\", service=\"kube-prometheus-stack-kubelet\"}",
     "legendFormat": "{{container}} memory usage"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"challenger-005\", pod=~\"nginx-.*\", container=\"nginx\", resource=\"memory\"}",
     "legendFormat": "{{container}} memory requests"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"challenger-005\", pod=~\"nginx-.*\", container=\"nginx\", resource=\"memory\"}",
     "legendFormat": "{{container}} memory limits"
    }
   ]
  }
 ]
}